-- +goose Up
-- +goose StatementBegin
INSERT INTO interests (name, category, icon_url)
VALUES
    ('Gym', 'fitness', NULL),
    ('Running', 'fitness', NULL),
    ('Yoga', 'fitness', NULL),
    ('Pilates', 'fitness', NULL),
    ('Hiking', 'outdoors', NULL),
    ('Camping', 'outdoors', NULL),
    ('Cycling', 'outdoors', NULL),
    ('Swimming', 'sports', NULL),
    ('Football', 'sports', NULL),
    ('Basketball', 'sports', NULL),
    ('Tennis', 'sports', NULL),
    ('Skiing', 'outdoors', NULL),
    ('Snowboarding', 'outdoors', NULL),
    ('Surfing', 'outdoors', NULL),
    ('Travel', 'travel', NULL),
    ('Road Trips', 'travel', NULL),
    ('Photography', 'arts', NULL),
    ('Painting', 'arts', NULL),
    ('Movies', 'entertainment', NULL),
    ('Reading', 'culture', NULL),
    ('Writing', 'culture', NULL),
    ('Live Music', 'music', NULL),
    ('Concerts', 'music', NULL),
    ('Singing', 'music', NULL),
    ('Guitar', 'music', NULL),
    ('Cooking', 'food', NULL),
    ('Baking', 'food', NULL),
    ('Coffee', 'food', NULL),
    ('Brunch', 'food', NULL),
    ('Wine', 'food', NULL),
    ('Dancing', 'social', NULL),
    ('Board Games', 'games', NULL),
    ('Gaming', 'games', NULL),
    ('Dogs', 'lifestyle', NULL),
    ('Cats', 'lifestyle', NULL),
    ('Fashion', 'lifestyle', NULL),
    ('Meditation', 'wellness', NULL),
    ('Volunteering', 'community', NULL),
    ('Tech', 'career', NULL),
    ('Startups', 'career', NULL)
ON CONFLICT (name) DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DELETE FROM interests
WHERE name IN (
    'Gym',
    'Running',
    'Yoga',
    'Pilates',
    'Hiking',
    'Camping',
    'Cycling',
    'Swimming',
    'Football',
    'Basketball',
    'Tennis',
    'Skiing',
    'Snowboarding',
    'Surfing',
    'Travel',
    'Road Trips',
    'Photography',
    'Painting',
    'Movies',
    'Reading',
    'Writing',
    'Live Music',
    'Concerts',
    'Singing',
    'Guitar',
    'Cooking',
    'Baking',
    'Coffee',
    'Brunch',
    'Wine',
    'Dancing',
    'Board Games',
    'Gaming',
    'Dogs',
    'Cats',
    'Fashion',
    'Meditation',
    'Volunteering',
    'Tech',
    'Startups'
);
-- +goose StatementEnd
