server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    location /healthz {
        proxy_pass http://api-gateway-winx:3000/healthz;
    }

    location /register {
        proxy_pass http://api-gateway-winx:3000/register;
        proxy_set_header X-API-Key winx-key;
    }

    location /login {
        proxy_pass http://api-gateway-winx:3000/login;
        proxy_set_header X-API-Key winx-key;
    }

    location /check {
        proxy_pass http://api-gateway-winx:3000/check;
        proxy_set_header X-API-Key winx-key;
    }

    location /profile {
        proxy_pass http://api-gateway-winx:3000/profile;
        proxy_set_header X-API-Key winx-key;
    }
}